sudo: required
services:
  - docker

before_install:
  - docker build -t hmeyyur/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hmeyyur/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstack
  region: "us-east-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-664525274212"
  bucket_path: "docker" 
  on:
    branches:
		- master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"